config/routes.rb
Rails.application.routes.draw do
  get 'items/warehouse'
  get 'appointment/get_appointment'
  devise_for :users
  resources :friends
  #get 'home/index'
  get 'home/about'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointment_controller.rb
class AppointmentController < ApplicationController
  def get_appointment
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end


  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def warehouse
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointment_helper.rb
module AppointmentHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/appointment/get_appointment.html.erb
<h1>Appointment#get_appointment</h1>
<p>Do you see this?</p>

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <% form.label :first_name ,class: 'form-label' %>
    <%= form.text_field :first_name ,class: "form-control", placeholder: "First Name" %>
  </div>

  <div class="field mb-3">
    <% form.label :last_name ,class: 'form-label' %>
    <%= form.text_field :last_name ,class: "form-control", placeholder: "Last Name" %>
  </div>

  <div class="field mb-3">
    <% form.label :email ,class: 'form-label' %>
    <%= form.text_field :email ,class: "form-control", placeholder: "Email" %>
  </div>

  <div class="field mb-3">
    <% form.label :phone ,class: 'form-label' %>
    <%= form.text_field :phone ,class: "form-control", placeholder: "Phone" %>
  </div>

  <br>
  <div class="actions">
    <%= form.submit class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/friends/edit.html.erb
<h1>Editing Friend</h1>

<br/>
<%= render 'form', friend: @friend %>

<br/>
<%= link_to 'Show', @friend, class: "btn btn-primary" %> 
<%= link_to 'Back', friends_path, class: "btn btn-primary" %>

app/views/friends/index.html.erb
<div class="table-responsive">
<table class="table table-hover">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @friends.each do |friend| %>
      <tr>
        <td><%= friend.first_name %></td>
        <td><%= friend.last_name %></td>
        <td><%= friend.email %></td>
        <td><%= friend.phone %></td>
        <td><%= link_to 'Show', friend %></td>
        <td><%= link_to 'Edit', edit_friend_path(friend) %></td>
        <td><%= link_to 'Destroy', friend, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<%= link_to 'New Friend', new_friend_path, class:"btn btn-outline-dark"%>

app/views/friends/new.html.erb
<h1>Add new Friend</h1>
<br>

<%= render 'form', friend: @friend, class:"btn btn-outline-dark" %>

<br>
<%= link_to 'Back', friends_path, class:"btn btn-primary" %>

app/views/friends/show.html.erb
<div class="card text-center">
  <div class="card-header">
    Details
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= @friend.first_name %>  <%= @friend.last_name %></h5>
    
    <p class="card-text">
      <b>e-mail:</b>
        <%= @friend.email %>
      </p>
      <p class="card-text">
      <b>Telefono:</b>
        <%= @friend.phone %>
      </p>

    <%= link_to 'Edit', edit_friend_path(@friend), class:"btn btn-outline-dark" %> 
    <%= link_to 'Back', friends_path, class:"btn btn-outline-dark" %>

  </div>
  <div class="card-footer text-muted">
   Footer
  </div>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Friend App', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
        
        <li class="nav-item">
        <%= link_to 'About Us', home_about_path, class:"nav-link" %> 
        </li>

        <% if user_signed_in? %>
        <li class="nav-item">
        <%= link_to 'Friends', friends_path, class:"nav-link" %> 
        </li>

        <li class="nav-item">
        <%= link_to 'New Friend', new_friend_path, class:"nav-link" %> 
        </li>
        
        <li class="nav-item">
        <%= link_to 'Sign Out',  destroy_user_session_path, method: :delete,  class:"nav-link" %> 
        </li>

         <li class="nav-item">
        <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link" %> 
        </li>
          
        <li class="nav-item">
        <%= link_to 'Get an Appointment', appointment_get_appointment_path, class:"nav-link" %> 
        </li>


        <% else %>
         <li class="nav-item">
        <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link" %> 
        </li>

         <li class="nav-item">
        <%= link_to 'Sign In', new_user_session_path, class:"nav-link" %> 
        </li>

        <% end %>

         

        

      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us...</h1>

app/views/home/index.html.erb
<h1>Hello World</h1>
<p>My first web page...</p>

app/views/items/warehouse.html.erb
<h1>Items#warehouse</h1>
<p>Find me in app/views/items/warehouse.html.erb</p>

app/views/layouts/_alerts.html.erb
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
  </symbol>
  <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
  </symbol>
  <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
  </symbol>
</svg>

<div class="alert alert-success d-flex align-items-center alert-dismissible fade show" role="alert">
  <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"/></svg>
  <div>
    <%= notice %>
  </div>
   <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Friends App</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  
  <%= render 'home/header' %>
  <div class ="container">
  

    <% if notice %>
      <%= render 'layouts/alerts' %>
      <% end %>
  
    <br/>
      <%= yield %>
     </div>
     </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>